_class_path:
    value: src.my_model.transformer.TrackFormer
_instantiator:
    value: lightning.pytorch.cli.instantiate_module
_wandb:
    value:
        cli_version: 0.18.2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 55
                - 106
            "2":
                - 1
                - 55
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.6
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
criterion:
    value: mse
dropout:
    value: 0
input_dim:
    value: 3
input_dropout:
    value: 0
lr:
    value: 0.003
max_iters:
    value: 2
model_dim:
    value: 128
num_classes:
    value: 1
num_heads:
    value: 4
num_layers:
    value: 4
warmup:
    value: 100
