# lightning.pytorch==2.4.0
seed_everything: 0
## Dataset
data:
  class_path: src.datasets.datamodules.DataModule
  init_args:
    dataset_type: tml
    dataset_dir: Data/Tml/train_1
    batch_size: 1024
    use_wrapper: False
    persistance: True