# lightning.pytorch==2.4.0
seed_everything: 0
trainer:
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  num_nodes: 1
  precision: 32
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args: 
        save_dir: Models/TrackML
        default_hp_metric: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: src.utils.ParmSummary
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: model-{epoch:02d}-{val_loss:.2f}
        monitor: val_loss
        verbose: false
        save_top_k: 1
        save_weights_only: false
        mode: min
ckpt_path: "last"
