# lightning.pytorch==2.4.0
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args: 
        save_dir: Data/Tb
        default_hp_metric: false
        name: acts-final  ## same name
  callbacks:
    - class_path: lightning.pytorch.callbacks.Timer
      init_args:
        duration: "00:01:00:00" 
        interval: "step" 
        verbose: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: src.utils.ParmSummary
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: Data/Tb
        filename: model-{epoch:02d}-{val_loss:.2f}
        monitor: val_loss
        verbose: True
        save_top_k: 1
        save_weights_only: false
        mode: min
  fast_dev_run: false
  max_epochs: 12
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  log_every_n_steps: 1

# model
model:
  class_path: src.my_model.transformer.TrackFormer
  init_args:
    input_dim: 3
    model_dim: 200
    num_classes: 1
    num_heads: 4
    num_layers: 2
    criterion: qloss-0.5
    max_iters: 160 ## always check try to make automatic
    warmup: 100
    lr: 0.0002
    dropout: 0.1
    input_dropout: 0.1
    
    ## Dataset
data:
  class_path: src.datasets.datamodules.ActsDataModule
  init_args:
    batch_size: 2048
    num_workers: 16
    persistence: false
ckpt_path: last
