model:
  class_path: src.my_model.transformer.TrackFormer
  init_args:
    input_dim: 3
    model_dim: 128
    num_classes: 1
    num_heads: 4
    num_layers: 4
    criterion: "mse"
    max_iters: 2
    warmup: 100
    lr: 0.003
    dropout: 0.0
    input_dropout: 0.0