trainer:
  accelerator: auto
  devices: auto
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: "mse-loss"
      project: TrackFormer
  callbacks: 
    class_path: src.utils.ParmSummary 
    class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: "model-{epoch:02d}-{val_loss:.2f}"
      save_top_k: 1
      verbose: False
      monitor: "val_loss"
      mode: "min"
  precision: "32"
  max_epochs: 2
ckpt_path: "last"
