trainer:
  accelerator: auto
  num_workers: 10
  devices: auto
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: "mse-loss"
      project: TrackFormer
  callbacks: 
    class_path: src.utils.ParmSummary 
  precision: "32"
  max_epochs: 2
ckpt_path: "last"
